services:
  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ...:/output
    ports: 
      - 5010:5000
    environment:
      - HA_BASE_URL=...
      - HA_SCREENSHOT_URL=...?kiosk
      - HA_ACCESS_TOKEN=eyJ...
      - HA_BATTERY_WEBHOOK=...
      - LANGUAGE=en
      - TIMEZONE=America/Los_Angeles
      - CRON_JOB=* * * * *
      - RENDERING_TIMEOUT=30000
      - RENDERING_DELAY=0
      - RENDERING_SCREEN_HEIGHT=800
      - RENDERING_SCREEN_WIDTH=600
      - ROTATION=0
      - SCALING=1
      - GRAYSCALE_DEPTH=8
      - COLOR_MODE=TrueColor
      - OUTPUT_PATH=/output/dashboard.png
